require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
  TargetRubyVersion: 3.0

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
